server:
  port: 8082
spring:
  rabbitmq:
    queue:
      stock_queue:
        name: stock
      email_queue:
        name: email
    routing:
      stock:
        key: stock_routing_key
      email:
        key: email_routing_key
    exchange:
      name: order_exchange
